/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Demo1: typeof import('./src/components/q-button/doc/demo1.vue')['default']
    Demo2: typeof import('./src/components/q-button/doc/demo2.vue')['default']
    Demo3: typeof import('./src/components/q-button/doc/demo3.vue')['default']
    ElTree: typeof import('element-plus/es')['ElTree']
    Preview: typeof import('./src/components/preview/preview.vue')['default']
    QButton: typeof import('./src/components/q-button/index.vue')['default']
    QInput: typeof import('./src/components/q-input/index.vue')['default']
    QSelect: typeof import('./src/components/q-select/index.vue')['default']
    QTree: typeof import('./src/components/q-tree/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
